### PR TITLE
OVA deployment enhancements

### PR DESCRIPTION
**Pull request by kpschuck**
This does a few things:
1. Allows an optional `hostname` property to be used in the `ops_manager_deployment.yml`
   - when present, this will cause the `appliance_deployment.rb` to reset the target to `hostname` prior to provisioning the initial user.
   - This allows a DNS entry to be used to resolve Ops Manager (i.e. `opsmanager.systemdomain.mycompany.com`)
2. Catches some additional errors `CF::UAA::BadTarget, SocketError` when fetching the diagnostic report or the access token
3. Prevents NPE in `access_token` when `get_token` is nil

### CODE REVIEW

**Comment by kpschuck** [comment]
@bonzofenix - any thoughts on this one?

**Comment by bonzofenix** [comment]
Hi @kpschuck, 
I am really sorry for the delay on this. I will take a look today and try to merge it. Thank you.

**Comment by bonzofenix** [comment]
@kpschuck can you sign the CLA?
Thank you!

**Comment by geofffranks** [comment]
hey @kpschuck is this something you're still looking for? We can take a look at including this, but there're a bunch of merge conflicts + the CLA still needs to be signed.

**Comment by kpschuck** [comment]
@geofffranks - I'm going to rebase this from upstream, test out the changes and resubmit the PR

**Pull request closed without merging**
