### PR TITLE
De-duplicate stemcells list before downloading them

### PR DESCRIPTION
**Pull request by coryjett**
This is a simple change to de-duplicate the stemcells list before downloading them.  Speeds things up substantially if there are multiple products with the same stemcell.

### CODE REVIEW

**Comment by bonzofenix** [comment]
This looks good @coryjett . can you sign the CLA so I can merge it? Thank you

**Comment by coryjett** [comment]
I have signed it.  Thanks.

**Comment by coryjett** [comment]
Hi @bonzofenix.  I signed the CLA but it looks like the check never ran again.  Can you please verify?

**Comment by coryjett** [comment]
Closing this PR for now.  @kpschuck and I are maintaining a fork under his account at the moment and we can PR from there.

**Pull request closed without merging**
